from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / "files"
WINDOW_ICON_PATH = FILES_DIR / "icon.png"

FONT_SIZE_LG = 40
FONT_SIZE_MD = 24
FONT_SIZE_SM = 16

TEXT_MARGIN = 15

MINIMUM_WIDTH = 500

PRIMARY_COLOR = "#1e81b0"
DARKER_PRIMARY_COLOR = "#16658a"
DARKEST_PRIMARY_COLOR = "#115270"

