def print_lorem_ipsum():
    print(
        f"Lorem ipsum dolor sit amet, consectetur adipiscing elit." 
        f"Fusce vitae iaculis leo. Ut ac eros vel lectus placerat aliquet."
        f"Duis euismod non augue id varius." 
        f"Donec ullamcorper tempus sem, quis aliquet lacus sollicitudin a."
        f"Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."
        f"Nam eu orci scelerisque, placerat eros non, viverra mauris."
        f"In mollis enim at sapien pharetra, et bibendum odio tincidunt."
        f"Nullam consequat tempus justo quis efficitur."
        f"Praesent posuere enim ut consectetur maximus."
        f"Phasellus sit amet dui ex. Sed velit nibh, viverra nec tellus a, rhoncus dapibus lacus."
        f"Morbi euismod sapien sed ex interdum condimentum."
        f"Maecenas auctor condimentum metus, in tempor enim aliquet id."
        f"Praesent quam orci, tempus vel orci venenatis, volutpat accumsan mauris."
        f"Suspendisse tristique lacus diam, tincidunt fermentum risus rhoncus ut."
        f"Donec mi velit, semper sit amet sapien at, facilisis condimentum augue."
        f"Ut aliquet maximus lacus vitae lobortis."
        f"Integer placerat, diam quis pretium faucibus, risus urna tincidunt erat, eget semper tellus mauris at lectus."
        f"Pellentesque euismod nisi risus, vel posuere ligula volutpat non."
        f"Nulla venenatis dui eget odio tristique, at vestibulum justo interdum."
        f"Fusce convallis at mauris sed consectetur. Nulla facilisi."
        f"Nam pellentesque mi et metus cursus, sit amet pellentesque erat hendrerit."
        f"Donec eleifend rutrum massa nec varius."
        f"Praesent convallis turpis velit, vel imperdiet nulla molestie nec."
        f"Aenean vestibulum consequat nulla. Vivamus pharetra sapien eget tristique ullamcorper."
        f"Duis iaculis tincidunt arcu, a volutpat ante vestibulum et."
        f"Maecenas quis facilisis ex. Sed molestie facilisis libero."
        f"Aenean pulvinar aliquam justo, eu pulvinar libero pharetra ac."
        f"Integer ex justo, rhoncus eu turpis quis, consectetur gravida quam."
        f"Mauris gravida orci ac elit accumsan fringilla."
        f"Vivamus id pharetra felis, in faucibus sem. Aliquam erat volutpat."
    )