print("Hellor World", type("Hellor World"))
print(10, type(10))
print(22.0, type(22.0))
print(True, type(True))
print(10 != 10, type(10 != 10))
print("teste", type("teste"), bool("teste"))
print("22", type("22"), type(int("22")))

print("Nome:", "Alexandre", type("Alexandre") ,sep=" ")
print("Idade:", 29, type(29), sep=" ")
print("Altura:", 1.70, type(1.70), sep=" ")
print("Maior de idade:", 29 > 18, type(29 > 18), sep=" ")