print("Adição", 2 + 2)
print("Subtração", 10 - 3)
print("Multiplicação", 11 * 2)
print("MUltiplicação com 'polimorfismo'", 20*"x")
print("Divisão", 100 / 5)
print("Divisão inteira", 25 // 2)
print("Potência", 9 ** 2)
print("Módulo", 9 % 3)
print("Expressão matemática", (2 + 2) * 3)